module.exports = {
  ROLES: {
    ADMIN: 'admin',
    EMPLOYEE: 'employee',
    CA: 'ca',
    USER: 'user',
  },
  STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    LOCKED: 'locked',
  },
  ORDER_STATUSES: [
    'Pending',
    'Processing',
    'Manufacturing',
    'Packed',
    'Dispatched',
    'Delivered',
    'Cancelled',
    'Returned',
    'Refund',
    'Payment Pending',
    'Credit Pending',
  ],
  MEMO_STATUSES: [
    'Pending',
    'Approved',
    'Rejected',
    'Resolved',
  ],
  MEASUREMENT_TYPES: {
    SQFT: 'Sqft',
    SQIN: 'Sqin',
    SQM: 'Sqm',
  },
  PAYMENT_TYPES: {
    CASH: 'Cash',
    ONLINE: 'Online',
    CREDIT: 'Credit',
    PARTIAL: 'Partial',
  },
  EXPENSE_CATEGORIES: [
    'Electricity',
    'Water',
    'Internet',
    'Office Rent',
    'Fuel',
    'Maintenance',
    'Miscellaneous',
  ],
  TAXES: {
    DEFAULT_GST: parseFloat(process.env.DEFAULT_GST_PERCENT) || 5,
    DEFAULT_PST: parseFloat(process.env.DEFAULT_PST_PERCENT) || 7,
  },
  ALL_PERMISSIONS: [
    'Dashboard',
    'Products',
    'Categories',
    'Orders',
    'Customers',
    'Invoices',
    'Credit List',
    'GST',
    'PST',
    'Reports',
    'Accounts',
    'Expenses',
    'Salary',
    'Loans',
    'Employees',
    'Settings',
    'History',
    'PDF Download',
    'Print Invoice',
    'Delete',
    'Create',
    'Edit',
    'View',
    'Export',
    'Import',
    'Role Management',
    'Backup',
    'Restore',
    'Analytics',
    'Customer Pricing',
    'Tax Reports',
    'Payment',
    'Advance Payment',
    'Partial Payment',
    'Credit Payment',
    'COD Management',
    'Memo Management',
    'Notification',
  ],
};
